# Generated by Django 4.0.6 on 2022-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='설명')),
                ('content', models.TextField(verbose_name='내용')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
