# Generated by Django 4.0.6 on 2022-07-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-modify_dt'], 'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
    ]
