# Generated by Django 4.0.6 on 2022-08-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
